[CaseData]
git-tree-sha1 = "b2e5ec0a5e5dabe0d5b7864fe743f410d5e0d224"
lazy = true

    [[CaseData.download]]
    url = "https://github.com/NREL-SIIP/PowerSystemsTestData/archive/refs/tags/2.0-alpha.tar.gz"
    sha256 = "b997642874dc3a5fc7c5b25f9270a03ef38473ea5acfd4e814e1a8ede4be9fad"

[rts]
git-tree-sha1 = "5098f357bad765bfefcff58f080818863ca776bd"
lazy = true

    [[rts.download]]
    url = "https://github.com/GridMod/RTS-GMLC/archive/refs/tags/v0.2.2.tar.gz"
    sha256 = "f7a816f2390b96d44fa931c2790e2ec5ef81d0deb503c4c719b25ec1b585e2c2"
